### PR TITLE
Adds teosd.service to run teos as daemon

### PR DESCRIPTION
**Pull request by sr-gi**
This builds on top of the work from the work by @decentralizedb and @jochemin in #138. It is mainly just re-arranging the code and readmes to fit https://github.com/talaia-labs/rust-teos/pull/138#pullrequestreview-1195570409, but they did all the heavy lifting.

Close #138

### CODE REVIEW

**Comment by sr-gi** [comment]
@jochemin @decentralizedb you may want to give this a look

**Comment by sr-gi** [comment]
Hey @jochemin @decentralizedb @lunaticoin, this is the only thing blocking `v0.2.0`, can you give it a try?

**Comment by decentralizedb** [comment]
I tried this configuration, and it worked.
Just one comment, the lines:
After=bitcoind.service
After=network.target

It's equivalent to having:
After=network.target bitcoind.service

I suggest changing it because it's clearer to read putting both options on the same line.
For the rest, everything worked without any problem.

**Comment by sr-gi** [comment]
Addressed comments and rebased master

**Pull request merged**
