### PR TITLE
Adds getsubscriptioninfo to the CLN plugin

### PR DESCRIPTION
**Pull request by sr-gi**
From https://github.com/talaia-labs/rust-teos/pull/82#pullrequestreview-1059016422

### CODE REVIEW

**Review by meryacine — CHANGES_REQUESTED** [review]
Let's add some docs about this command in the [watchtower plugin's readme](https://github.com/talaia-labs/rust-teos/blob/master/watchtower-plugin/README.md).
LGTM otherwise.

**Comment by meryacine** [comment]
Also [this](https://github.com/talaia-labs/rust-teos/blob/master/watchtower-plugin/README.md?plain=1#L12) should spell `listtowers` not `list_towers`. Can we fix it in the PR?

**Comment by sr-gi** [comment]
> Also [this](https://github.com/talaia-labs/rust-teos/blob/master/watchtower-plugin/README.md?plain=1#L12) should spell `listtowers` not `list_towers`. Can we fix it in the PR?

Sure, will squeeze it here

**Comment by sr-gi** [comment]
@meryacine both issues should have been fixed in [d4a293f](https://github.com/talaia-labs/rust-teos/pull/86/commits/d4a293feb2d92edb48523acc68138452269f85e3)

**Pull request merged**
