### PR TITLE
Replace server.address() by server.base_url()

### LINKED ISSUE #61: Build MockServer endpoints using base_url() instead of address()
`httpmock::MockServer` is being used in several tests throughout the codebase when interaction with the http API is needed for testing purposes.

Currently, addresses to connect to the mocked server are built on the lines of :

```
let server = MockServer::start();

[...]

endpoint = format!("http://{}", server.address())
```

This can be simplified by using the `base_url()` method:

```
endpoint = server.base_url()
```

### PR DESCRIPTION
**Pull request by JonathanPlasse**
Close #61

### CODE REVIEW

**Review by sr-gi — APPROVED** [review]
LGTM

Needs rebasing

**Comment by sr-gi** [comment]
@JonathanPlasse can you rebase master and force push so this can be merged?

**Comment by JonathanPlasse** [comment]
Rebase done.

**Comment by sr-gi** [comment]
Hey @JonathanPlasse, we require all commits to be signed in order to merge them into the main branch. Please check https://github.com/talaia-labs/rust-teos/blob/master/CONTRIBUTING.md#signing-commits and rebase + recommit please.

**Comment by sr-gi** [comment]
@JonathanPlasse I completely missed that you addressed this. Sorry.

If you can rebase to be up to date with master I'll merge this.

**Comment by JonathanPlasse** [comment]
Rebased.

**Pull request merged**
