### PR TITLE
Makes sure generated blocks have valid pow

### LINKED ISSUE #56: Blockchain::at_height may return invalid data
`Blockchain::at_height` may pull a `BlockHeader` that cannot be verified. This have been seen in CI in rare occasions.

Not a big deal, but it may be nice to find the root of the error so tests do not fail randomly on CI.

```
---- watcher::tests::test_cache_fix stdout ----
thread 'watcher::tests::test_cache_fix' panicked at 'called `Result::unwrap()` on an `Err` value: BlockSourceError { kind: Persistent, error: BlockBadProofOfWork }', teos/src/test_utils.rs:163:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    watcher::tests::test_cache_fix

test result: FAILED. 149 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 25.68s
```

### PR DESCRIPTION
**Pull request by sr-gi**
Close #56

### CODE REVIEW

**Comment by sr-gi** [comment]
@meryacine you may be interested

**Comment by meryacine** [comment]
ACK [`63dd0f0`](https://github.com/talaia-labs/rust-teos/pull/67/commits/63dd0f074b856f9b42ff468d8d02b50228b2bcf3).
I was kinda hesitant going the way of changing the `nonce` since I see it is used [here](https://github.com/talaia-labs/rust-teos/blob/0ba8aa141dd97d1e1043878d3b4bf5c354901c93/teos/src/test_utils.rs#L149) to denote forks. But apparently the tests didn't fail :).

**Comment by sr-gi** [comment]
>  I was kinda hesitant going the way of changing the `nonce` since I see it is used [here](https://github.com/talaia-labs/rust-teos/blob/0ba8aa141dd97d1e1043878d3b4bf5c354901c93/teos/src/test_utils.rs#L149) to denote forks. But apparently the tests didn't fail :).

I think that's just a way of changing the blockhash while maintaining the rest of the data in the block (i.e. having two exact blocks mined with a different hash)

**Comment by meryacine** [comment]
Ooops. I believe you are right.

**Pull request merged**
