### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by carboncls**

### CODE REVIEW

**Comment by sr-gi** [comment]
@carboncls Thanks for giving this a look. Please add a minimal description to the PR.

**Comment by carboncls** [comment]
ok, I'm sorry, I'm very new to github and I'm not sure I know what to do here ... if you want, you can just correct this minor typo in the README without this PR.

**Comment by meryacine** [comment]
@carboncls You can:
- Clone your fork, do the changes in the PR branch, push them to github (or force push them to keep the commit history clean), and they will automatically appear in this PR.
- Go to your fork on github, do the changes in the PR branch from github's editor and commit them, and they will automatically appear in this PR. This way a maintainer will have to squash the PR into one commit when merging it.

**Comment by sr-gi** [comment]
@carboncls no worries, try to make the changes and, if you don't manage, I'll edit the description and squash the commits myself.

**Comment by sr-gi** [comment]
@carboncls can you patch the comments and rebase? I can do it myself otherwise.

**Comment by carboncls** [comment]
yes, I was busy with other stuff and didn't really know what to do. sorry for the confusion and thank you for the change.

**Comment by sr-gi** [comment]
No problem. Thank you for catching the typos.

**Pull request closed without merging**
